events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://app1:80;
        }
                          
        location /app2/ { 
            proxy_pass http://app2:80/;
        }
    }
}
