name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check required files exist
        run: |
          test -f docker-compose.yaml
          test -f proxy/nginx.conf
          test -f app1/index.html
          test -f app2/index.html

      - name: Validate Docker Compose
        run: docker compose -f docker-compose.yaml config

      - name: Validate NGINX config
        run: |
          cp proxy/nginx.conf proxy/nginx.test.conf
          sed -i 's/app1/127.0.0.1/g' proxy/nginx.test.conf
          sed -i 's/app2/127.0.0.1/g' proxy/nginx.test.conf

          docker run --rm \
            -v ${{ github.workspace }}/proxy/nginx.test.conf:/etc/nginx/nginx.conf:ro \
            nginx:latest nginx -t
           
      - name: Start application stack
        run: docker compose -f docker-compose.yaml up -d

      - name: wait for services
        run: sleep 10

      - name: Test main app
        run: |
          curl -f http://localhost | grep "My First DevOps Server"

      - name: Test app2 route
        run: |
          curl -f http://localhost/app2/ | grep "App 2 Running"

      - name: show container status
        if: always()
        run: docker compose -f docker-compose.yaml ps

      - name: show container logs
        if: failure()
        run: docker compose -f docker-compose.yaml logs
            
      - name: Tear down stack
        if: always()
        run: docker compose -f docker-compose.yaml down
